[phases.setup]
nixPkgs = ["python312", "postgresql", "gcc"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
# ÖNEMLİ: Tablo yoksa, önce migrate et, sonra gunicorn ile sunucuyu başlat.
# Bu komutun başarısız olma ihtimali çok düşüktür.
cmd = "python manage.py migrate --noinput && gunicorn okul_kulupleri.wsgi"